### ISSUE TITLE
Missing return statement

### ISSUE THREAD

**Issue by Workshop2** [AshleyPoole/Noobot.Modules#1]
Good work btw 👍 

You should return the "IndicateTyping" with a yield return:
https://github.com/AshleyPoole/Noobot.Modules/blob/324f915eb27339b70e5e04b914c6b45516136726/src/Noobot.Modules.Dns/DnsMiddleware.cs#L37

**Comment by AshleyPoole** [comment]
Thanks, good catch! Just fixed it.

**Comment by AshleyPoole** [comment]
1.0.2 of DNS, LoadBalancerDotOrg and NewRelic module.
1.0.1 of IncidentManagement module.
